//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use chrono::Utc;
use sea_orm::{entity::prelude::*, Set};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "seller_profile")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub legal_name: String,
    pub commercial_name: Option<String>,
    pub address: Option<String>,
    pub city: Option<String>,
    pub phone_number: Option<String>,
    pub email: Option<String>,
    pub ice: Option<String>,
    pub if_number: Option<String>,
    pub rc: Option<String>,
    pub patente: Option<String>,
    pub logo: Option<String>,
    pub default_currency: String,
    pub default_payment_terms_days: i32,
    pub invoice_footer: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {
    fn new() -> Self {
        Self {
            id: Set(ulid::Ulid::new().to_string()),
            created_at: Set(Utc::now().naive_utc()),
            updated_at: Set(Utc::now().naive_utc()),
            default_currency: Set("MAD".to_string()),
            default_payment_terms_days: Set(30),
            ..ActiveModelTrait::default()
        }
    }
}
