//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use chrono::Utc;
use sea_orm::{entity::prelude::*, Set};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "clients")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub full_name: String,
    pub created_at: DateTime,
    pub is_deleted: bool,
    pub phone_number: Option<String>,
    pub email: Option<String>,
    pub address: Option<String>,
    pub image: Option<String>,
    pub ice: Option<String>,
    pub if_number: Option<String>,
    pub rc: Option<String>,
    pub patente: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::delivery_notes::Entity")]
    DeliveryNotes,
    #[sea_orm(has_many = "super::invoices::Entity")]
    Invoices,
    #[sea_orm(has_many = "super::orders::Entity")]
    Orders,
    #[sea_orm(has_many = "super::quotes::Entity")]
    Quotes,
}

impl Related<super::delivery_notes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeliveryNotes.def()
    }
}

impl Related<super::invoices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Invoices.def()
    }
}

impl Related<super::orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Orders.def()
    }
}

impl Related<super::quotes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Quotes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {
    fn new() -> Self {
        Self {
            id: Set(ulid::Ulid::new().to_string()),
            created_at: Set(Utc::now().naive_utc()),
            ..ActiveModelTrait::default()
        }
    }
}