//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::{Set, entity::prelude::*};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "invoice_items")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub invoice_id: String,
    #[sea_orm(column_type = "Text")]
    pub product_id: String,
    pub price: Decimal,
    pub quantity: Decimal,
    #[sea_orm(column_type = "Text", nullable)]
    pub inventory_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::inventory_transactions::Entity",
        from = "Column::InventoryId",
        to = "super::inventory_transactions::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    InventoryTransactions,
    #[sea_orm(
        belongs_to = "super::invoices::Entity",
        from = "Column::InvoiceId",
        to = "super::invoices::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Invoices,
    #[sea_orm(
        belongs_to = "super::products::Entity",
        from = "Column::ProductId",
        to = "super::products::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Products,
}

impl Related<super::inventory_transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InventoryTransactions.def()
    }
}

impl Related<super::invoices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Invoices.def()
    }
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl ActiveModelBehavior for ActiveModel {
    fn new() -> Self {
        Self {
            id: Set(ulid::Ulid::new().to_string()),
            ..Default::default()
        }
    }
}