//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod clients;
pub mod inventory_transactions;
pub mod invoice_items;
pub mod invoices;
pub mod order_items;
pub mod orders;
pub mod products;
pub mod quote_items;
pub mod quotes;
pub mod suppliers;
pub mod templates;
