//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod clients;
pub mod inventory_transactions;
pub mod invoice_items;
pub mod invoice_payments;
pub mod invoices;
pub mod order_items;
pub mod orders;
pub mod products;
pub mod quote_items;
pub mod quotes;
pub mod templates;
pub mod user_column_preferences;
