//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "order_items")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    pub price: Decimal,
    #[sea_orm(column_type = "Text")]
    pub order_id: String,
    #[sea_orm(column_type = "Text", unique)]
    pub inventory_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::inventory_transactions::Entity",
        from = "Column::InventoryId",
        to = "super::inventory_transactions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    InventoryTransactions,
    #[sea_orm(
        belongs_to = "super::orders::Entity",
        from = "Column::OrderId",
        to = "super::orders::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Orders,
}

impl Related<super::inventory_transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InventoryTransactions.def()
    }
}

impl Related<super::orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Orders.def()
    }
}

impl ActiveModelBehavior for ActiveModel {
    fn new() -> Self {
        Self {
            id: sea_orm::ActiveValue::Set(ulid::Ulid::new().to_string()),
            ..Default::default()
        }
    }
}
