use specta_typescript::Typescript;
use tauri::Runtime;
use tauri_specta::{collect_commands, Builder};

use crate::commands;

pub fn builder<R: Runtime>() -> Builder<R> {
    Builder::<R>::new().commands(collect_commands![
        commands::products::list_products,
        commands::products::search_products,
        commands::products::create_product,
        commands::products::update_product,
        commands::products::delete_product,
        commands::databases::list_databases,
        commands::databases::get_database_bootstrap_status,
        commands::databases::get_active_database,
        commands::databases::create_database,
        commands::databases::switch_database,
        commands::inventory::list_inventory,
        commands::inventory::create_inventory,
        commands::inventory::void_inventory_transaction,
        commands::clients::list_clients,
        commands::clients::list_client_invoice_debts,
        commands::clients::search_clients,
        commands::clients::get_client,
        commands::clients::create_client,
        commands::clients::update_client,
        commands::clients::delete_client,
        commands::delivery_notes::list_delivery_notes,
        commands::delivery_notes::list_delivery_note_products,
        commands::delivery_notes::get_delivery_note,
        commands::delivery_notes::create_delivery_note_from_order,
        commands::credit_notes::create_credit_note,
        commands::credit_notes::list_credit_notes,
        commands::credit_notes::get_credit_note,
        commands::orders::list_orders,
        commands::orders::get_order,
        commands::orders::get_order_details,
        commands::orders::create_order,
        commands::orders::update_order,
        commands::orders::delete_order,
        commands::orders::list_order_products,
        commands::orders::create_order_from_quote,
        commands::orders::update_order_status,
        commands::quotes::list_quotes,
        commands::quotes::get_quote,
        commands::quotes::get_quote_details,
        commands::quotes::create_quote,
        commands::quotes::update_quote,
        commands::quotes::delete_quote,
        commands::quotes::list_quote_products,
        commands::templates::create_template,
        commands::quote_items::delete_quote_item,
        commands::order_items::delete_order_item,
        commands::invoices::list_invoices,
        commands::invoices::get_invoice,
        commands::invoices::get_invoice_details,
        commands::invoices::create_invoice,
        commands::invoices::update_invoice,
        commands::invoices::add_invoice_payment,
        commands::invoices::delete_invoice,
        commands::invoices::list_invoice_products,
        commands::invoices::create_invoice_from_delivery_note,
        commands::invoices::update_invoice_status,
        commands::invoices::finalize_invoice,
        commands::invoice_items::delete_invoice_item,
        commands::dashboard::list_inventory_stats,
        commands::dashboard::list_top_clients,
        commands::dashboard::list_top_products,
        commands::dashboard::list_status_count,
        commands::dashboard::list_financial_metrics,
        commands::column_preferences::get_column_preferences,
        commands::column_preferences::save_column_preferences,
        commands::seller_profile::get_seller_profile,
        commands::seller_profile::update_seller_profile,
        commands::seed::seed_database,
    ])
}

pub fn export_bindings() {
    builder::<tauri::Wry>()
        .export(
            Typescript::default().header("// Generated by tauri-specta\n// Do not edit manually!"),
            "../app/bindings.ts", // adjust path if your frontend folder is different
        )
        .expect("failed to export tauri specta bindings");
}

#[cfg(test)]
mod tests {
    #[test]
    fn export_typescript_bindings() {
        super::export_bindings();
    }
}
